---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-bgp-config
  namespace: kube-system
spec:
  interval: 10m
  dependsOn:
    - name: cilium
      namespace: kube-system
  path: ./kubernetes/apps/kube-system/cilium/bgp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 3m
  wait: true
