---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  releaseName: kube-prometheus-stack
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 77.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: cilium
        hosts:
          - alertmanager.${SECRET_DOMAIN}
        tls:
          - secretName: ${SECRET_DOMAIN/./-}-production-tls
            hosts:
              - alertmanager.${SECRET_DOMAIN}
    grafana:
      enabled: true
      adminPassword: ${SECRET_GRAFANA_PASSWORD}
      ingress:
        enabled: true
        ingressClassName: cilium
        hosts:
          - grafana.${SECRET_DOMAIN}
        tls:
          - secretName: ${SECRET_DOMAIN/./-}-production-tls
            hosts:
              - grafana.${SECRET_DOMAIN}
    prometheus:
      prometheusSpec:
        retention: 30d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
      ingress:
        enabled: true
        ingressClassName: cilium
        hosts:
          - prometheus.${SECRET_DOMAIN}
        tls:
          - secretName: ${SECRET_DOMAIN/./-}-production-tls
            hosts:
              - prometheus.${SECRET_DOMAIN}
