---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1x2a4tsdepv882cexzv5kv5js883tp2jqthezzpkvjur5wwnsgv0sgjndtw"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1x2a4tsdepv882cexzv5kv5js883tp2jqthezzpkvjur5wwnsgv0sgjndtw"
stores:
  yaml:
    indent: 2
