---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-traefik
  namespace: network
spec:
  interval: 10m
  dependsOn:
    - name: kube-system-cilium
      namespace: kube-system
  path: ./kubernetes/apps/network/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m
  wait: true
