---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-traefik
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: kube-system-clilium
  path: ./kubernetes/apps/network/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
