---
# BGP Cluster Configuration using v2 API
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: mikrotik-bgp
spec:
  nodeSelector:
    matchLabels: {}
  bgpInstances:
  - name: "main"
    localASN: 64514
    peers:
    - name: "mikrotik"
      peerASN: 64513
      peerAddress: "172.16.20.1"
---
# BGP Advertisement for Pod CIDRs
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: pod-advertisement
spec:
  advertisements:
  - advertisementType: "PodCIDR"
---
# BGP Advertisement for LoadBalancer Services
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: service-advertisement
spec:
  advertisements:
  - advertisementType: "Service"
    service:
      addresses:
      - LoadBalancerIP
    selector:
      matchExpressions:
      - key: io.kubernetes.service.type
        operator: In
        values:
        - LoadBalancer
