---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: mikrotik-bgp-cluster-config
spec:
  nodeSelector:
    matchLabels: {}
  bgpInstances:
  - name: "mikrotik-bgp-instance"
    localASN: 64520
    peers:
    - name: "mikrotik-router"
      peerASN: 64510
      peerAddress: "172.16.20.1"
      peerConfigRef:
        name: "mikrotik-router-config"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: mikrotik-router-config
spec:
  families:
    - afi: "ipv4"
      safi: "unicast"
      advertisements:
        matchLabels:
          advertise-pod-cidr: "true"
          advertise-lb-service: "true"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: pod-cidr-advertisement
  labels:
    advertise-pod-cidr: "true"
spec:
  advertisements:
  - advertisementType: "PodCIDR"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: loadbalancer-advertisement
  labels:
    advertise-lb-service: "true"
spec:
  advertisements:
  - advertisementType: "Service"
    service:
      addresses:
      - LoadBalancerIP
      - ExternalIP
    selector:
      matchLabels:
        io.kubernetes.service/type: LoadBalancer
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: mikrotik-lb-pool
spec:
  blocks:
  - cidr: "10.41.100.0/24"
  serviceSelector:
    matchLabels:
      advertise-lb-service: "true"
