---
# BGP Peering Policy for MikroTik
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: mikrotik-peering
spec:
  nodeSelector:
    matchLabels: {}  # Apply to all nodes
  virtualRouters:
  - localASN: 64514
    exportPodCIDR: true
    serviceSelector:
      matchExpressions:
      - key: io.kubernetes.service.type
        operator: In
        values:
        - LoadBalancer
    neighbors:
    - peerASN: 64513
      peerAddress: "172.16.20.1"
      connectRetryTime: "30s"
      holdTime: "90s"
      keepAliveTime: "30s"
---
# LoadBalancer IP Pool
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: primary-pool
spec:
  blocks:
  - cidr: "172.16.20.220/30"  # .220-.223
  serviceSelector:
    matchExpressions:
    - key: io.kubernetes.service.type
      operator: In
      values:
      - LoadBalancer
---
# L2 Announcement Policy (replaces MetalLB)
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
spec:
  serviceSelector:
    matchExpressions:
    - key: io.kubernetes.service.type
      operator: In
      values:
      - LoadBalancer
  nodeSelector:
    matchLabels: {}  # All nodes can announce
  interfaces:
  - ^eth[0-9]+
  - ^ens[0-9]+
  externalIPs: true
  loadBalancerIPs: true
