---
# Primary LoadBalancer IP Pool (replaces MetalLB)
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: primary-pool
spec:
  allowFirstLastIPs: "Yes"  # Allow .220 and .223
  blocks:
    - cidr: "172.16.20.220/30"  # .220, .221, .222, .223
  serviceSelector:
    matchExpressions:
    - key: io.kubernetes.service.type
      operator: In
      values:
      - LoadBalancer
---
# L2 Announcement Policy (replaces MetalLB L2Advertisement)
apiVersion: cilium.io/v2
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
spec:
  loadBalancerIPs: true
  externalIPs: true
  # Interfaces will be auto-detected, but you can specify if needed:
  # interfaces:
  #   - ^eth[0-9]+
  #   - ^ens[0-9]+
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
