---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "172.16.20.0/24"
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  # NOTE: interfaces might need to be set if you have more than one active NIC on your hosts
  # interfaces:
  #   - ^eno[0-9]+
  #   - ^eth[0-9]+
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumbgpclusterconfig_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: mikrotik-bgp-cluster-config
spec:
  nodeSelector:
    matchLabels: {}
  bgpInstances:
  - name: "mikrotik-bgp-instance"
    localASN: 64520
    peers:
    - name: "mikrotik-router"
      peerASN: 64510
      peerAddress: "172.16.20.1"
      timers:
        connectRetryTimeSeconds: 120
        holdTimeSeconds: 240
        keepAliveTimeSeconds: 80
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
      families:
      - afi: ipv4
        safi: unicast
        advertisements:
          matchLabels:
            advertise-pod-cidr: "true"
            advertise-lb-service: "true"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: pod-cidr-advertisement
  labels:
    advertise-pod-cidr: "true"
spec:
  advertisements:
  - advertisementType: "PodCIDR"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: loadbalancer-advertisement
  labels:
    advertise-lb-service: "true"
spec:
  advertisements:
  - advertisementType: "Service"
    service:
      addresses:
      - LoadBalancerIP
      - ExternalIP
    selector:
      matchLabels:
        io.kubernetes.service/type: LoadBalancer
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: mikrotik-lb-pool
spec:
  blocks:
  - cidr: "10.41.100.0/24"
  serviceSelector:
    matchLabels:
      io.kubernetes.service/type: LoadBalancer
