---
# Primary LoadBalancer IP Pool (BGP advertised only)
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: primary-pool
spec:
  allowFirstLastIPs: "Yes"  # Allow .220 and .223
  blocks:
    - cidr: "172.16.20.220/30"  # .220, .221, .222, .223
  serviceSelector:
    matchExpressions:
    - key: io.kubernetes.service.type
      operator: In
      values:
      - LoadBalancer
