---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-metallb-config
  namespace: network
spec:
  interval: 10m
  dependsOn:
    - name: network-metallb
      namespace: network
  path: ./kubernetes/apps/network/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 3m
  wait: true
