# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: UDNYS25TMDJMZGlYSjJtYgo=
  AWS_SECRET_ACCESS_KEY: RTR4NGdSM1Z2amQzTGtHaldUNnpjSWN6QWNTTkZlZWcK
  AWS_ENDPOINTS: aHR0cDovL3N5bm9sb2d5Lm14ZTExLm5sOjkwMDEK
