apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "1.15.x"   # pick a stable version from the repo
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    # Run external-dns as a Deployment in kube-system
    serviceAccount:
      create: true
      name: external-dns

    provider: rfc2136
    policy: sync
    registry: txt
    txtOwnerId: talos-cl01
    domainFilters:
      - apps.corp.matjah.dev

    rfc2136:
      host: 172.16.20.53
      port: 53
      zone: apps.corp.matjah.dev
      tsigKeyName: apps-ddns-key.     # trailing dot is important
      tsigSecretSecretRef:
        name: externaldns-tsig
        key: secret
      tsigSecretAlg: hmac-sha256

    # optional: tune resources
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # optional: set log verbosity
    logLevel: debug
