---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-values
  namespace: default
data:
  values.yaml: |
    defaultSettings:
      defaultReplicaCount: 1
    persistence:
      reclaimPolicy: Delete
      defaultReplicaCount: 1
      defaultClass: true
    service:
      ui:
        type: LoadBalancer
        port: 80
