---
deployment:
  replicas: 2

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

service:
  type: NodePort
  spec:
    externalTrafficPolicy: Local
  ports:
    web:
      nodePort: 30080
    websecure:
      nodePort: 30443

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.web.proxyProtocol.trustedIPs=172.16.20.0/24"
  - "--entrypoints.web.forwardedHeaders.trustedIPs=172.16.20.0/24"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

  - "--entrypoints.websecure.address=:443"
  - "--entrypoints.websecure.proxyProtocol.trustedIPs=172.16.20.0/24"
  - "--entrypoints.websecure.forwardedHeaders.trustedIPs=172.16.20.0/24"

  # Good defaults
  - "--serversTransport.insecureSkipVerify=true"
  - "--api.dashboard=true"

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true

metrics:
  prometheus:
    enabled: true

# Disable built-in ACME (we will use cert-manager + Vault)
certificatesResolvers: {}

tolerations: []
affinity: {}
