apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HkWMyBz245L1vA==,iv:15KVGotvzHgl5dEIe7h0lQ/B7B4cQU471FiFDC3AysA=,tag:GpJFINAFSEIMW3EEtptEVg==,type:str]
sops:
  age:
    - recipient: age1x2a4tsdepv882cexzv5kv5js883tp2jqthezzpkvjur5wwnsgv0sgjndtw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJODBEQW9oYlNhS2krL0I2
        V2U4Y2xJSGlOY245ZGRlQkZmRllLUW9sSXpNCnoyMWF0amxLZXBPUUhvanZ5R0ZX
        c3N6WkVVcDcydHZ0T1F2OXFrdm1GTWsKLS0tIGhUUkpsVkx0U3ZCbEIzM1p2VlBh
        bDNFVTltV3g4SDlzajd4ZlY2S2xhWDgKacuuZzmzm0HU8NS/FZCuBYnagTrOxD2c
        NkXVG7tdz9rl09wcei40xAUaFyp5vL/tTgmHlVv7+NaNifV0C7ilBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-17T20:59:30Z"
  mac: ENC[AES256_GCM,data:CrBfxPjI72I5W/FVBFrXG0devR5f0bYyd2rZ7ROEeNsnTUS5wAr1MhGjRl+JMcrs3f9/IWeoFsfzV1g1RaGLUa0ICeuRvF4JjBZjZ1iVaVCtTqRk6aSyvJP/JSgNPOZRuYfTc2/AzqHbi35LTYKItz1csTRI5wanFY/kE9ku8eI=,iv:P9CG74Z1ozNXGiS+Tgq6dHFqQrwmDgn4qNa4wmgZ3DM=,tag:Ey/PyL1jicRQpD4p67CE5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
