apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/kube-system/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops       # <-- adjust to match your GitRepository object
    namespace: flux-system
  targetNamespace: kube-system
  wait: true
